server:
  port: 8080
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: safe-env
  datasource:
    username: user2
    password: password
    url: jdbc:postgresql://localhost:5432/safe_env
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5

logging:
  level:
    com=INFO: